version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "E:/Course AI Software Engineer/Curs-AI-Software-Engineer/Capitolul 12:/workspace"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.0
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns